apiVersion: skaffold/v2alpha3
kind: Congig
deploy:
    kubectl:
        manifests:
            -   ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        -   image: cisco008/client
            context: client
            docker:
                dockerfile: Dockerfile
            sync:
                manual:
                    -   src: 'src/**/*.js'
                        dest: .
        -   image: cisco008/comments
            context: comments
            docker:
                dockerfile: Dockerfile
            sync:
                manual:
                    -   src: '*.js'
                        dest: .
        -   image: cisco008/event-bus
            context: event-bus
            docker:
                dockerfile: Dockerfile
            sync:
                manual:
                    -   src: '*.js'
                        dest: .
        -   image: cisco008/moderation
            context: moderation
            docker:
                dockerfile: Dockerfile
            sync:
                manual:
                    -   src: '*.js'
                        dest: .
        -   image: cisco008/posts
            context: posts
            docker:
                dockerfile: Dockerfile
            sync:
                manual:
                    -   src: '*.js'
                        dest: .
        -   image: cisco008/query
            context: query
            docker:
                dockerfile: Dockerfile
            sync:
                manual:
                    -   src: '*.js'
                        dest: .